### ISSUE TITLE
Migration to API version 2.0

### ISSUE THREAD

**Issue by martabrz** [jvfe/pytrials#14]
- pytrials version: 0.3.0
- Python version: 3.10.13
- Operating System: MacOS Sonoma 14.1.2 

### Description
As stated in [API Migration Guide](https://clinicaltrials.gov/data-api/about-api/api-migration), the classical API will be retired in July this year. Due to ongoing outages, the connection via classical API does not work all the time. Similarly to issue #9, upon instantiating the `ClinicalTrials` trials, I get `RequestsJSONDecodeError`.

### What I tried
I changed `BASE_URL` attribute to `https://clinicaltrials.gov/api/v2/`, but this is not sufficient; I believe the other variables in init should be changed as well.

**Comment by neurokrish** [comment]
I have the same issue as well. Is there a fix in progress?

**Comment by jvfe** [comment]
This will require a whole refactor of how the requests and data are handled within the package. So it will be a major update.

Either way it will **take a while**, since I don't have a lot of time available to dedicate to this project. So if anyone wants to take this up, they're welcome to do so.

**Comment by jvfe** [comment]
A quick fix is done through [release 1.0.0](https://github.com/jvfe/pytrials/releases/tag/v1.0.0). Since the API changed so significantly it is a breaking change though, so most old code based on the package will have to be changed.
