### ISSUE TITLE
Study_fields is not Valid

### ISSUE THREAD

**Issue by sumirp** [jvfe/pytrials#17]
* pytrials version: 1.0.0
* Python version: 3.12.3
* Operating System: macOS sonoma 14.5

### Description

I am trying to extract data for a search term using the get_study_fields function, mentioning the field names and the format I want the data is "json", but I am getting an error message "An error occurred: One of the fields is not valid!Check the study_fields attribute for a list of valid ones.They are different depending on the return format, json or csv." 
I printed the get_study_fields function and re-checked the names of the fields I want and they are the same.

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by jvfe** [comment]
Hi, could you share which fields you're using?

**Comment by sumirp** [comment]
I am trying to get ('NCTId', 'BriefTitle', 'OverallStatus', 'StartDate', 'Phase', 'StudyType', 'InterventionName', 'Condition', 'LocationCountry')

**Comment by sumirp** [comment]
Is something wrong with the library ?

**Comment by jvfe** [comment]
Hi, I'm able to request the fields you require just fine:

```python
from pytrials.client import ClinicalTrials
ct = ClinicalTrials()
results = ct.get_study_fields(
    search_expr="Coronavirus+COVID",
    fields=['NCTId', 'BriefTitle', 'OverallStatus', 'StartDate', 'Phase', 'StudyType', 'InterventionName', 'Condition', 'LocationCountry'],
    max_studies=1000,
    fmt="json",
)

print(results)
```

**Comment by sumirp** [comment]
Hi, Thank you I can see the data now
