### ISSUE TITLE
output format CSV causes a ValueError exception

### ISSUE THREAD

**Issue by radaniba** [jvfe/pytrials#19]
* pytrials version: 1.0.0
* Python version: 3.9.16
* Operating System: MacOS

### Description
I am running a basic example and I got issues where fmt is CSV

The basic example is like follows :

```python
study_fields2 = ct.get_study_fields(
    search_expr="Mother OR Infant OR newborn OR Vaccine OR Immunity",
    fields=[
        "NCTId",
        "EnrollmentCount", 
        "PrimaryOutcomeMeasure", 
        "LocationFacility", 
        "LocationCity", 
        "LocationState", 
        "LocationZip", 
        "LocationCountry",
      
    ],
    max_studies=999,
    fmt="csv" # Tis doesn't work, but when it is "json" it does
)

```
# The error message :

ValueError: One of the fields is not valid!Check the study_fields attribute for a list of valid ones.They are different depending on the return format, json or csv.

Which is strange because the fields are the same and they work when it is json

Any idea ?

Cheers

Rad

**Comment by jvfe** [comment]
Hi, try the following:

```py
study_fields2 = ct.get_study_fields(
    search_expr="Mother OR Infant OR newborn OR Vaccine OR Immunity",
    fields=[
        "NCT Number",
        "Enrollment",
        "Primary Outcome Measures",
        "Locations"
    ],
    max_studies=999,
    fmt="csv"
)
```

It should have the information you require.
Unfortunately as of the latest version of the API, the fields in JSON and CSV are not the same, check here: https://github.com/jvfe/pytrials/blob/master/pytrials/fields.csv for a mapping between the two.

**Comment by radaniba** [comment]
Thanks @jvfe for the very fast response that makes sense

**Comment by radaniba** [comment]
@jvfe do you know how to add the name of the principal investigators in there ? (contacts ?)

I used to use these fields before 

```
       "LocationContactName", 
        "CentralContactName", 
        "OverallOfficialName",
        "CentralContactEMail", 
        "CentralContactPhone", 
        "CentralContactRole"

```
but with the new update I think they are broken ?

**Comment by jvfe** [comment]
Sorry, not sure, with the new API update I couldn't find those.

**Comment by radaniba** [comment]
All good @jvfe thanks for your help anyways :) yeah that update broke a couple of things indeed :) well ..
