### ISSUE TITLE
SSLError: HTTPSConnectionPool(host='clinicaltrials.gov', port=443)

### ISSUE THREAD

**Issue by OleksiyAnokhin** [jvfe/pytrials#3]
### Description

Tried to did a basic request from the tutorial 

### What I Did

# Get 50 full studies related to Coronavirus and COVID in json format.
ct.get_full_studies(search_expr="Coronavirus+COVID", max_studies=50)

```
Got error

SSLError: HTTPSConnectionPool(host='clinicaltrials.gov', port=443): Max retries exceeded with url: /api/info/data_vrs?fmt=json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1125)')))
```

**Comment by jvfe** [comment]
Looks unrelated to the package. Examples run fine on my machine and on the CI. 

Must be a local issue on your end, take a look at the following links, might help you:
- https://stackoverflow.com/questions/50236117/scraping-ssl-certificate-verify-failed-error-for-http-en-wikipedia-org?noredirect=1&lq=1
- https://stackoverflow.com/questions/51925384/unable-to-get-local-issuer-certificate-when-using-requests-in-python
